Exit code: 1
Stdout:

Search operators to employ:
genetic_crossover(probability=[0.9],angle=[22.5],sigma=[0.1]) with greedy
swarm_dynamic(factor=[0.7, 1.0],self_conf=[2.54],swarm_conf=[2.56],version=['inertial', 'constriction'],distribution=['uniform', 'gaussian', 'levy']) with metropolis
--------------------------------------------------

Stderr:
Traceback (most recent call last):
  File "/Users/valeriaenriquezlimon/Documents/research-llm/llm-metaheuristics/ollama_output_20241001_232448/execution_iteration_2.py", line 34, in <module>
    met.run()
  File "/Users/valeriaenriquezlimon/Documents/research-llm/llm-metaheuristics/metaheuristic.py", line 143, in run
    self.apply_search_operator(perturbator, selector)
  File "/Users/valeriaenriquezlimon/Documents/research-llm/llm-metaheuristics/metaheuristic.py", line 99, in apply_search_operator
    exec('Operators.' + operator_name + '(self.pop,' + operator_params)
  File "<string>", line 1, in <module>
TypeError: genetic_crossover() got an unexpected keyword argument 'probability'
